### ISSUE TITLE
License declaration

### ISSUE THREAD

**Issue by bob-carpenter** [codatmo/UNINOVE_Sao_Paulo#1]
Nobody will be able to use any code that's included in this repo unless there's an open-source license.   The declared license also governs contributions under GitHub's terms of service.

All that is needed is a `LICENSE.md` file in the top-levle directory, though I believe you can also select a licenase in the web interface.

When there's a license, I'll submit my code.  Thanks!

**Comment by storopoli** [comment]
@breckbaldwin from UNINOVE's side we can go with whatever LICENSE you would like for CoDatMo.

**Comment by storopoli** [comment]
Since other CoDatMo repositories have a BSD-3-Clause License, we will do the same? Does that works for you Bob?

**Comment by bob-carpenter** [comment]
BSD 3 is great.  Thanks much!

**Comment by bob-carpenter** [comment]
By default on GitHub,
* the code author or their assignee maintain copyright on their contributin, and
* the code the author agrees by submitting a PR to release the code they contribute under the license indicated for the repo.

In order for "copyright codatmo" to make sense (also it's 2021 now, not 2020), codatmo would need to be a legal entity with the ability to own assets like copyrights.  Second, anyone making a contribution would have to assign copyright to codatmo through a separate agreement in order for codatmo to legally own the copyright. Submitting the PR doesn't transfer copyright by default.

Most university researchers in the U.S. (for instance, all the Columbia research employees like Breck or Andrew) assign their copyright for code to their employer as part of their employment agreement (rules are typically different for students and for lecturers).  So they'd have to get the university to agree to assign copyright to codatmo.  Same for me and Flatiron.

So I'd suggest just changing "codatmo" to "Code Authors" and then everything works as expected by default (assuming you expect code authors or their assignees to maintain copyright).

Hope that helps.

**Comment by storopoli** [comment]
You are absolutely right. I haven't thought of this. Thanks! Done. I will close the issue now. Feel free to reopen if necessary.
